=== ARLM-Attic/vart/applications/BodySim_Windows/bin/Debug/vpat.dtd
<!-- DTD for an articulated human body for Project VPat -->
<!-- Author: Anderson Maciel - Apr 25, 2001 - Jun 13,2001 -->

<!ELEMENT vpat ( body+, movement* )>

<!ELEMENT body ( joint+ )>

<!ELEMENT joint ( dof*, shape* )>

<!ELEMENT dof ( position, axis, range, comfort_range?, evoluta?, modifier? )>

<!ELEMENT shape ( position, iaxis, jaxis, kaxis )>

<!ELEMENT position EMPTY>

<!ELEMENT axis EMPTY>

<!ELEMENT iaxis EMPTY>
<!ELEMENT jaxis EMPTY>
<!ELEMENT kaxis EMPTY>

<!ELEMENT range EMPTY>

<!ELEMENT comfort_range EMPTY>

<!ELEMENT evoluta ( ctrl_point* )>

<!ELEMENT ctrl_point EMPTY>

<!ATTLIST body description CDATA #REQUIRED
							 file_name CDATA "">
							
<!ATTLIST joint description CDATA #REQUIRED
								parent			CDATA #REQUIRED
								type 				( uniaxial|biaxial|polyaxial|plane ) #REQUIRED >

<!ATTLIST dof description CDATA #REQUIRED >

<!ATTLIST shape description CDATA #REQUIRED
							  file_name CDATA #REQUIRED >

<!ATTLIST position x CDATA #REQUIRED
							  	 y CDATA #REQUIRED
							  	 z CDATA #REQUIRED >
							  	
<!ATTLIST ctrl_point	x		CDATA #REQUIRED
							  	 		y		CDATA #REQUIRED
							  	 		z 	CDATA #REQUIRED >
							  	
<!ATTLIST axis x CDATA #REQUIRED
							 y CDATA #REQUIRED
							 z CDATA #REQUIRED >
							
<!ATTLIST iaxis x CDATA #REQUIRED
							  y CDATA #REQUIRED
							  z CDATA #REQUIRED >

<!ATTLIST jaxis x CDATA #REQUIRED
							  y CDATA #REQUIRED
							  z CDATA #REQUIRED >
							
<!ATTLIST kaxis x CDATA #REQUIRED
							  y CDATA #REQUIRED
							  z CDATA #REQUIRED >
							
<!ATTLIST range min CDATA #REQUIRED
							  max CDATA #REQUIRED >

<!ATTLIST comfort_range min 	CDATA #REQUIRED
							  				max		CDATA #REQUIRED
							  				rest	CDATA #REQUIRED >

<!ELEMENT modifier ( relation+ )>

<!ELEMENT relation ( ctrl_point, ctrl_point, ctrl_point, ctrl_point,
										 ctrl_point, ctrl_point, ctrl_point, ctrl_point  )>

<!ATTLIST relation dof CDATA #REQUIRED >

<!ELEMENT movement ( motion* ) >

<!ATTLIST movement body_name  CDATA #REQUIRED
                   cycle      CDATA #REQUIRED
                   delta_t    CDATA #REQUIRED
                   time_err   CDATA #REQUIRED >

<!ELEMENT motion EMPTY>

<!ATTLIST motion joint_name   CDATA #REQUIRED
                 t0           CDATA #REQUIRED
                 tf           CDATA #REQUIRED
                 type         CDATA #REQUIRED
                 parameter    CDATA #REQUIRED
                 interpolation  CDATA "" >

=== ARLM-Attic/vart/core/examples/BodySim/windows/hebe4.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE vpat SYSTEM "vpat.dtd">

<vpat>
<body description="John" file_name="john.xml" >
   <joint description="root" parent="null" type="uniaxial">
       <dof description="no_move">
         <position x="0.0" y="0.0" z="0.0"/>
         <axis x="1.0" y="0.0" z="0.0"/>
         <range min="0" max="0"/>
         <comfort_range min="0.0" max="0.0" rest="0.0"/>
      </dof>
      <shape description="skull" file_name="cranio.iv">
         <position x="0.0" y="0.0" z="0.0"/>
         <iaxis x="1.0" y="0.0" z="0.0"/>
         <jaxis x="0.0" y="1.0" z="0.0"/>
         <kaxis x="0.0" y="0.0" z="1.0"/>
      </shape>
	  </joint>
	  <joint description="skull_mandi" parent="root" type="biaxial">
	   <dof description="flexionK">
           <position x="0.0" y="20.00" z="0.0"/>
            <axis x="1.0" y="0.0" z="0.0"/>
			<range min="-0.01" max="0.03"/>
		 </dof>	
	 
      <shape description="jaw" file_name="mandibula.iv">
            <position x="0.0" y="20.00" z="0.00"/>
            <iaxis x="1.0" y="0.0" z="0.0"/>
            <jaxis x="0.0" y="1.0" z="0.0"/>
            <kaxis x="0.0" y="0.0" z="1.0"/>
         </shape>     
   </joint>
  
   
</body>
<movement body_name="john" cycle="on" delta_t="0.01" time_err="0.0001"> 
<motion joint_name="skull_mandi" t0="-0.01" tf="0.2" type="FLEX" parameter="0.0"/>
<motion joint_name="skull_mandi" t0="0.31" tf="0.40" type="ADUCT" parameter="0.6"/>
  <!-- set motion -->
</movement>
</vpat>

=== ARLM-Attic/vart/applications/BodySim_Windows/bin/win1.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE vpat SYSTEM "vpat.dtd">

<vpat>
<body description="Joelho" file_name="valida3.xml" >
   <joint description="root" parent="null" type="uniaxial">
      <dof description="no_move">
         <position x="0.0" y="0.0" z="0.0"/>
         <axis x="1.0" y="0.0" z="0.0"/>
         <range min="0.0" max="0.0"/>
         <comfort_range min="0.0" max="0.0" rest="0.0"/>
      </dof>
      <shape description="Femur" file_name="femurascii.iv">
         <position x="0.0" y="0.0" z="0.0"/>
         <iaxis x="1.0" y="0.0" z="0.0"/>
         <jaxis x="0.0" y="1.0" z="0.0"/>
         <kaxis x="0.0" y="0.0" z="1.0"/>
      </shape>
   </joint>
   <joint description="femur_tibia" parent="root" type="biaxial">
         <dof description="flexionK">
            <position x="168.86" y="74.04" z="-60.23"/>
            <axis x="0.0" y="0.0" z="1.0"/>
            <range min="-0.26" max="1.8"/>
            <evoluta>
               <ctrl_point x="-2.5" y="0.5" z="0.0"/>
               <ctrl_point x="-1.5" y="0.0" z="0.0"/>
               <ctrl_point x="4.0" y="0.0" z="0.0"/>
               <ctrl_point x="4.5" y="-0.5" z="0.0"/>
            </evoluta>
         </dof>
         <dof description="twistK">
            <position x="0.0" y="0.0" z="0.0"/>
            <axis x="0.0" y="1.0" z="0.0"/>
            <range min="-0.281" max="0.281"/>
            <modifier>
    						<relation dof="flexionK">
                   <ctrl_point x="0.0" y="0.0" z="0.0"/>
                   <ctrl_point x="1.0" y="0.0" z="0.0"/>
                   <ctrl_point x="2.0" y="0.0" z="0.0"/>
                   <ctrl_point x="3.0" y="0.0" z="0.0"/>
                   <ctrl_point x="0.0" y="0.0" z="0.0"/>
                   <ctrl_point x="0.0" y="0.28" z="0.0"/>
                   <ctrl_point x="0.0" y="0.28" z="0.0"/>
                   <ctrl_point x="3.0" y="0.28" z="0.0"/>
                </relation>
            </modifier>
         </dof>
         <shape description="Tibia" file_name="tibia_r.iv">
            <position x="-168.86" y="-74.04" z="60.23"/>
            <iaxis x="1.0" y="0.0" z="0.0"/>
            <jaxis x="0.0" y="1.0" z="0.0"/>
            <kaxis x="0.0" y="0.0" z="1.0"/>
         </shape>
         <shape description="Fibula" file_name="fibula_r.iv">
            <position x="-168.86" y="-74.04" z="60.23"/>
            <iaxis x="1.0" y="0.0" z="0.0"/>
            <jaxis x="0.0" y="1.0" z="0.0"/>
            <kaxis x="0.0" y="0.0" z="1.0"/>
         </shape>
   </joint>
   <joint description="femur_min" parent="femur_tibia" type="uniaxial">
      <dof description="flexionH">
         <position x="0.0" y="4.0" z="0.0"/>
         <axis x="0.0" y="0.0" z="1.0"/>
         <range min="0.0" max="0.0"/>
         <evoluta>
            <ctrl_point x="-5.0" y="0.0" z="0.0"/>
            <ctrl_point x="-2.0" y="0.0" z="0.0"/>
            <ctrl_point x="1.0" y="0.0" z="0.0"/>
            <ctrl_point x="3.0" y="0.0" z="0.0"/>
         </evoluta>
      </dof>
      <shape description="Menisco Lateral" file_name="Minuscus_lat_r.iv">
         <position x="-168.86" y="-78.04" z="60.23"/>
         <iaxis x="1.0" y="0.0" z="0.0"/>
         <jaxis x="0.0" y="1.0" z="0.0"/>
         <kaxis x="0.0" y="0.0" z="1.0"/>
      </shape>
      <shape description="Menisco Medial" file_name="Minuscus_med_r.iv">
         <position x="-168.86" y="-78.04" z="60.23"/>
         <iaxis x="1.0" y="0.0" z="0.0"/>
         <jaxis x="0.0" y="1.0" z="0.0"/>
         <kaxis x="0.0" y="0.0" z="1.0"/>
      </shape>
   </joint>
   <joint description="femur_patella" parent="femur_min" type="uniaxial">
         <dof description="flexionA">
            <position x="-50.0" y="0.0" z="0.0"/>
            <axis x="0.0" y="0.0" z="1.0"/>
            <range min="0.0" max="-0.8"/>
            <evoluta>
               <ctrl_point x="60.0" y="20.0" z="-2.0"/>
               <ctrl_point x="65.0" y="20.0" z="-4.0"/>
               <ctrl_point x="70.0" y="0.0" z="6.0"/>
               <ctrl_point x="75.0" y="-15.0" z="6.0"/>
            </evoluta>
         </dof>
         <shape description="Patela" file_name="patella_r.iv">
            <position x="-167.00" y="-74.04" z="60.23"/>
            <iaxis x="1.0" y="0.0" z="0.0"/>
            <jaxis x="0.0" y="1.0" z="0.0"/>
            <kaxis x="0.0" y="0.0" z="1.0"/>
         </shape>
   </joint>
</body>

<movement body_name="john" cycle="on" delta_t="0.01" time_err="0.0001">

  <!-- set start position -->
  <motion joint_name="femur_tibia" t0="-0.9" tf="0.0" type="ADDUCT" parameter="0.5"/>

  <!-- set motion -->
  <motion joint_name="femur_tibia" t0="0.0" tf="1.2" type="FLEX" parameter="0.0"/>
  <motion joint_name="femur_tibia" t0="1.3" tf="2.5" type="FLEX" parameter="1.0"/>
  <motion joint_name="femur_min" t0="0.0" tf="1.2" type="FLEX" parameter="0.0"/>
  <motion joint_name="femur_min" t0="1.3" tf="2.5" type="FLEX" parameter="1.0"/>
  <motion joint_name="femur_patella" t0="0.0" tf="1.2" type="FLEX" parameter="0.0"/>
  <motion joint_name="femur_patella" t0="1.3" tf="2.5" type="FLEX" parameter="1.0"/>
</movement>
</vpat>

=== ARLM-Attic/vart/core/examples/BodySim/windows/joe.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE vpat SYSTEM "vpat.dtd">

<vpat>
<body description="Joe" file_name="joe.xml" >
   <joint description="root" parent="null" type="uniaxial">
      <dof description="pronation">
         <position x="0.0" y="0.0" z="0.0"/>
         <axis x="0.0" y="0.0" z="1.0"/>
         <range min="0.0" max="1.0"/>
         <comfort_range min="0.2" max="0.8" rest="0.0"/>
         <evoluta>
            <ctrl_point x="0.0" y="0.0" z="0.0"/>
            <ctrl_point x="0.2" y="0.0" z="0.0"/>
            <ctrl_point x="0.4" y="0.0" z="0.0"/>
            <ctrl_point x="0.6" y="0.0" z="0.0"/>
         </evoluta>
      </dof>
      <shape description="Left Ulna" file_name="lulna.iv">
         <position x="0.0" y="0.0" z="0.0"/>
         <iaxis x="1.0" y="0.0" z="0.0"/>
         <jaxis x="0.0" y="1.0" z="0.0"/>
         <kaxis x="0.0" y="0.0" z="1.0"/>
      </shape>
   </joint>
   <joint description="pulse" parent="root" type="biaxial">
         <dof description="flexion">
            <position x="0.7" y="-9.65" z="1.6"/>
            <axis x="0.0" y="0.0" z="1.0"/>
            <range min="-0.7" max="0.7"/>
            <comfort_range min="-0.3" max="0.4" rest="0.0"/>
         </dof>
         <dof description="adduction">
            <position x="0.0" y="0.5" z="0.0"/>
            <axis x="1.0" y="0.0" z="0.0"/>
            <range min="-0.4" max="0.4"/>
            <comfort_range min="-0.8" max="1.0" rest="0.0"/>
            <modifier>
    						<relation dof="flexion">
                   <ctrl_point x="0.0" y="0.0" z="0.0"/>
                   <ctrl_point x="1.0" y="-0.4" z="0.0"/>
                   <ctrl_point x="2.0" y="-0.4" z="0.0"/>
                   <ctrl_point x="3.0" y="0.0" z="0.0"/>
                   <ctrl_point x="0.0" y="0.0" z="0.0"/>
                   <ctrl_point x="1.0" y="0.4" z="0.0"/>
                   <ctrl_point x="2.0" y="0.4" z="0.0"/>
                   <ctrl_point x="3.0" y="0.0" z="0.0"/>
                </relation>
            </modifier>
         </dof>
         <shape description="Left Hand" file_name="lhand.iv">
            <position x="0.0" y="0.0" z="0.0"/>
            <iaxis x="1.0" y="0.0" z="0.0"/>
            <jaxis x="0.0" y="1.0" z="0.0"/>
            <kaxis x="0.0" y="0.0" z="1.0"/>
         </shape>
   </joint>
</body>
</vpat>

=== ARLM-Attic/vart/core/examples/BodySim/windows/move.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE vpat SYSTEM "vpat.dtd">

<vpat>
  <body>
    <joint>
    </joint>
  </body>
  <movement body_name="john" cycle="off" delta_t="0.05" time_err="0.0001">
    <motion joint_name="root" t0="0.0" tf="1.0" type="FLEX" parameter="0.0">
    <motion joint_name="root" t0="7.0" tf="10.0" type="FLEX" parameter="1.0">
    <motion joint_name="knee" t0="2.0" tf="3.0" type="FLEX" parameter="0.0">
    <motion joint_name="knee" t0="3.1" tf="5.5" type="FLEX" parameter="1.0">
    <motion joint_name="knee" t0="5.6" tf="10.0" type="FLEX" parameter="0.0">
    <motion joint_name="ankle" t0="1.0" tf="1.5" type="TWIST" parameter="1.0">
    <motion joint_name="ankle" t0="1.6" tf="2.0" type="TWIST" parameter="0.0">
  </movement>
</vpat>

=== ARLM-Attic/vart/applications/BodySim_Windows/bin/Debug/bin/Cópia de john.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE vpat SYSTEM "vpat.dtd">

<vpat>
<body description="John" file_name="john.xml" >
   <joint description="root" parent="null" type="uniaxial">
      <dof description="flexionR">
         <position x="3.15" y="-118.2" z="-0.7"/>
         <axis x="1.0" y="0.0" z="0.0"/>
         <range min="0" max="0"/>
         <comfort_range min="0.2" max="0.8" rest="0.0"/>
      </dof>
      <shape description="skull" file_name="skull.iv">
         <position x="-3.15" y="8.2" z="0.7"/>
         <iaxis x="1.0" y="0.0" z="0.0"/>
         <jaxis x="0.0" y="1.0" z="0.0"/>
         <kaxis x="0.0" y="0.0" z="1.0"/>
      </shape>
   </joint>
   <joint description="mandi" parent="root" type="biaxial">
         <dof description="flexionK">
            <position x="-2.48" y="17.05" z="0.0"/>
            <axis x="1.0" y="0.0" z="0.0"/>
            <range min="0.0" max="0.0"/>
            <comfort_range min="-0.3" max="0.4" rest="0.0"/>
         </dof>
         <shape description="jawl" file_name="jaw.iv">
            <position x="-3.15" y="25.25" z="3.18"/>
            <iaxis x="1.0" y="0.0" z="0.0"/>
            <jaxis x="0.0" y="1.0" z="0.0"/>
            <kaxis x="0.0" y="0.0" z="1.0"/>
         </shape>     
   </joint>
</body>
<movement body_name="john" cycle="on" delta_t="0.05" time_err="0.0001"> 
<motion joint_name="mandi" t0="-1" tf="0.0" type="FLEX" parameter="1"/>
</movement>
</vpat>

=== ARLM-Attic/vart/core/examples/BodySim/windows/valida1.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE vpat SYSTEM "vpat.dtd">

<vpat>
<body description="John" file_name="john.xml" >
   <joint description="root" parent="null" type="uniaxial">
      <dof description="flexionR">
         <position x="3.15" y="-8.2" z="-0.7"/>
         <axis x="1.0" y="0.0" z="0.0"/>
         <range min="-1.8" max="1.0"/>
         <comfort_range min="0.2" max="0.8" rest="0.0"/>
      </dof>
      <shape description="Bacia" file_name="pelvis.iv">
         <position x="-3.15" y="8.2" z="0.7"/>
         <iaxis x="1.0" y="0.0" z="0.0"/>
         <jaxis x="0.0" y="1.0" z="0.0"/>
         <kaxis x="0.0" y="0.0" z="1.0"/>
      </shape>
   </joint>
   <joint description="hip" parent="root" type="uniaxial">
      <dof description="flexionH">
         <position x="0.0" y="0.0" z="0.0"/>
         <axis x="1.0" y="0.0" z="0.0"/>
         <range min="0.0" max="0.0"/>
         <comfort_range min="0.2" max="0.8" rest="0.0"/>
      </dof>
      <shape description="Femur" file_name="lfemur.iv">
         <position x="-3.15" y="8.2" z="0.7"/>
         <iaxis x="1.0" y="0.0" z="0.0"/>
         <jaxis x="0.0" y="1.0" z="0.0"/>
         <kaxis x="0.0" y="0.0" z="1.0"/>
      </shape>
   </joint>
   <joint description="knee" parent="hip" type="biaxial">
         <dof description="flexionK">
            <position x="-2.48" y="17.05" z="0.0"/>
            <axis x="1.0" y="0.0" z="0.0"/>
            <range min="0.0" max="2.2"/>
            <comfort_range min="-0.3" max="0.4" rest="0.0"/>
            <evoluta>
               <ctrl_point x="0.0" y="0.0" z="0.0"/>
               <ctrl_point x="-0.3" y="-0.3" z="0.0"/>
               <ctrl_point x="-0.2" y="-0.8" z="0.0"/>
               <ctrl_point x="0.1" y="-1.6" z="-0.5"/>
            </evoluta>
         </dof>
         <dof description="twistK">
            <position x="0.0" y="0.0" z="0.0"/>
            <axis x="0.0" y="1.0" z="0.0"/>
            <range min="0.0" max="0.28"/>
            <comfort_range min="-0.8" max="1.0" rest="0.0"/>
            <modifier>
    						<relation dof="flexionK">
                   <ctrl_point x="0.0" y="0.0" z="0.0"/>
                   <ctrl_point x="1.0" y="0.0" z="0.0"/>
                   <ctrl_point x="2.0" y="0.0" z="0.0"/>
                   <ctrl_point x="3.0" y="0.0" z="0.0"/>
                   <ctrl_point x="0.0" y="0.0" z="0.0"/>
                   <ctrl_point x="8.0" y="0.0" z="0.0"/>
                   <ctrl_point x="10.0" y="0.0" z="0.0"/>
                   <ctrl_point x="10.0" y="0.28" z="0.0"/>
                </relation>
            </modifier>
         </dof>
         <shape description="Tibia" file_name="ltibia.iv">
            <position x="-3.15" y="25.25" z="3.18"/>
            <iaxis x="1.0" y="0.0" z="0.0"/>
            <jaxis x="0.0" y="1.0" z="0.0"/>
            <kaxis x="0.0" y="0.0" z="1.0"/>
         </shape>
         <shape description="Patela" file_name="lpatella.iv">
            <position x="-3.15" y="25.45" z="3.18"/>
            <iaxis x="1.0" y="0.0" z="0.0"/>
            <jaxis x="0.0" y="1.0" z="0.0"/>
            <kaxis x="0.0" y="0.0" z="1.0"/>
         </shape>
         <shape description="Fibula" file_name="lfibula.iv">
            <position x="-3.15" y="25.25" z="3.18"/>
            <iaxis x="1.0" y="0.0" z="0.0"/>
            <jaxis x="0.0" y="1.0" z="0.0"/>
            <kaxis x="0.0" y="0.0" z="1.0"/>
         </shape>
   </joint>
   <joint description="ankle" parent="knee" type="biaxial">
         <dof description="flexionA">
            <position x="-1.0" y="15.25" z="-0.15"/>
            <axis x="1.0" y="0.0" z="0.0"/>
            <range min="0.0" max="1.0"/>
            <comfort_range min="-0.3" max="0.4" rest="0.0"/>
         </dof>
         <dof description="twistA">
            <position x="0.0" y="0.0" z="0.0"/>
            <axis x="0.0" y="0.0" z="1.0"/>
            <range min="-0.5" max="0.2"/>
            <comfort_range min="-0.8" max="1.0" rest="0.0"/>
         </dof>
         <shape description="Foot" file_name="lfoot.iv">
            <position x="-3.0" y="40.5" z="4.18"/>
            <iaxis x="1.0" y="0.0" z="0.0"/>
            <jaxis x="0.0" y="1.0" z="0.0"/>
            <kaxis x="0.0" y="0.0" z="1.0"/>
         </shape>
   </joint>			
</body>
<movement body_name="john" cycle="on" delta_t="0.05" time_err="0.0001">
  <motion joint_name="ankle" t0="-0.1" tf="0.0" type="FLEX" parameter="0.0"/>
  <motion joint_name="ankle" t0="-0.1" tf="0.0" type="ADDUCT" parameter="0.5"/>
  <motion joint_name="knee" t0="-0.1" tf="0.0" type="FLEX" parameter="0.0"/>
  <motion joint_name="knee" t0="-0.1" tf="0.0" type="ADDUCT" parameter="1.0"/>

  <motion joint_name="knee" t0="0.1" tf="8.0" type="FLEX" parameter="1.0"/>
  <motion joint_name="knee" t0="8.1" tf="16.0" type="FLEX" parameter="0.0"/>
</movement>
</vpat>
